require("config")    
require("keymaps")
require("packages")    
require("colors")    
require("plugins/telescope")
require("plugins/nvim-treesitter")
require("plugins/nvim-tree")
require("plugins/nvim-comment")
