require("config")
-- require("packages")
require("lazynvim")
require("keymaps")
require("colors")
require("plugins/alternate-toggler")
require("plugins/telescope")
require("plugins/nvim-treesitter")
require("plugins/nvim-tree")
require("plugins/nvim-comment")
require("plugins/trim")
require("plugins/nvim-cmp")
require("plugins/lsp")
require("plugins/null-ls")
